#!/bin/sh

set -e

cd -- "${0%/*}"

die() {
  printf '%s: %s\n' "${0##*/}" "$*" >&2
  exit 1
}

HOST=$(uname -m)

ZONE='/usr/share/zoneinfo/UTC'

REPO='https://repo-fastly.voidlinux.org/current/aarch64'

while getopts z:r:f opt; do
  case $opt in
    z)
      ZONE="$OPTARG"
      ;;
    r)
      REPO="${OPTARG}/current/aarch64"
      ;;
    f)
      HOST='aarch64'
      ;;
    *)
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

USB="$1"

if [ ! -d rootfs ]; then
  die "server files not found"
fi

if [ ! -f "$ZONE" ]; then
  die "timezone not found"
fi

if [ ! -b "$USB" ]; then
  die "usb drive not found"
fi

if [ "$HOST" != aarch64 ] && ! grep -q binfmt_misc /proc/mounts; then
  die "unsupported hardware"
fi

set -x

# format

wipefs -fa "$USB"
printf ', 512M, c\n,' | sfdisk "$USB"
udevadm settle

BOOTFS=$(blkid -s PARTUUID -o value "${USB}-part1")
ROOTFS=$(blkid -s PARTUUID -o value "${USB}-part2")

mkfs.vfat -F32 "${USB}-part1"
mkfs.xfs -f "${USB}-part2"

# mount

mount -o noatime "${USB}-part2" /mnt

mkdir /mnt/boot
mount -o noatime "${USB}-part1" /mnt/boot

mkdir /mnt/tmp
mount -o nosuid,nodev,noatime -t tmpfs tmpfs /mnt/tmp

mkdir /mnt/dev
mount --rbind /dev /mnt/dev
mount --make-rslave /mnt/dev

mkdir /mnt/sys
mount --rbind /sys /mnt/sys
mount --make-rslave /mnt/sys

mkdir /mnt/proc
mount --rbind /proc /mnt/proc
mount --make-rslave /mnt/proc

# void

mkdir -p /mnt/etc/xbps.d

printf "repository=%s\n" "$REPO" > /mnt/etc/xbps.d/00-repository-main.conf

{
  printf "ignorepkg=linux\n"
  printf "ignorepkg=linux-headers\n"
} > /mnt/etc/xbps.d/ignore.conf

mkdir -p /mnt/var/db/xbps/keys
cp -f /var/db/xbps/keys/* /mnt/var/db/xbps/keys/

XBPS_ARCH=aarch64-musl xbps-install -Syu -r /mnt \
  base-system \
  rpi-kernel \
  rpi-kernel-headers \
  rpi-firmware \
  rng-tools \
  chrony \
  rsync \
  curl \
  nano \
  htop \
  bottom \
  fastfetch \
  pfetch

ln -fs /etc/sv/rngd /mnt/etc/runit/runsvdir/default/
ln -fs /etc/sv/ntpd /mnt/etc/runit/runsvdir/default/
ln -fs /etc/sv/dhcpcd /mnt/etc/runit/runsvdir/default/
ln -fs /etc/sv/sshd /mnt/etc/runit/runsvdir/default/

printf "PermitRootLogin yes\n" > /mnt/etc/ssh/sshd_config.d/login.conf
printf "root:voidlinux\n" | chroot /mnt /bin/chpasswd -c SHA512

sed -i "s/root=[^ ]*/root=PARTUUID=${ROOTFS}/" /mnt/boot/cmdline.txt
printf "disable_splash=1\n" >> /mnt/boot/config.txt

printf "void\n" > /mnt/etc/hostname
ln -fs "$ZONE" /mnt/etc/localtime

{
  printf "tmpfs /tmp tmpfs nosuid,nodev,noatime 0 0\n"
  printf "PARTUUID=%s /boot vfat noatime 0 2\n" "$BOOTFS"
  printf "PARTUUID=%s / xfs noatime 0 0\n" "$ROOTFS"
} > /mnt/etc/fstab

{
  printf "printf 0 > /sys/class/leds/ACT/brightness\n"
  printf "printf 0 > /sys/class/leds/PWR/brightness\n"
} > /mnt/etc/rc.local

{
  printf "nameserver 1.1.1.1\n"
  printf "nameserver 1.0.0.1\n"
} > /mnt/etc/resolv.conf

printf 'OPTS="--nohook resolv.conf"\n' > /mnt/etc/sv/dhcpcd/conf

rsync -a --chown=root:root ./ /mnt/root/

sync

umount -R /mnt
