#!/bin/sh

set -e

fmt() {
  while [ $# -gt 0 ]; do
    curl -fsSL "$1"
    shift
  done |
    tr '[:upper:]' '[:lower:]' |
    sed -r \
      -e 's/\r$//' \
      -e 's/\s*!.*//g' \
      -e 's/\s*\[.*//g' \
      -e '/[a-z]\#[$?@]{0,1}\#/d' \
      -e 's/\s*#.*//g' \
      -e 's/^.*\s+//g' \
      -e '/^$/d' |
    sort -u
}

unbound_fmt() {
  awk '{print "local-zone: " $1 " always_null"}'
}

if [ $# -gt 0 ]; then
  fmt "$@"
else
  fmt https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
fi |
  unbound_fmt > deny.conf

wc -l < deny.conf
