#!/bin/sh

set -e

OUTPUT="./wireguard"
HOST_PORT=51820

gen_pre() {
  num1=$(openssl rand -hex 1)
  num2=$(openssl rand -hex 2)
  num3=$(openssl rand -hex 2)
  num4=$(openssl rand -hex 2)

  # printf 'fd%02x:%04x:%04x:%04x\n' "$num1" "$num2" "$num3" "$num4"
  printf 'fd%s:%s:%s:%s\n' "$num1" "$num2" "$num3" "$num4"
}

gen_ip() {
  int="$1"
  peer="$2"

  printf '%s::%x\n' "$WG_PREFIX" "$int"
  printf 'local-data: "%s AAAA %s::%x"\n' "$peer" "$WG_PREFIX" "$int" >> .unbound.conf
}

gen_wg() {
  HOST_ADDR=$(gen_ip 1 server)

  HOST_KEY=$(wg genkey)
  HOST_PUB=$(printf %s "$HOST_KEY" | wg pubkey)

  {
    out "[Interface]"
    out "PrivateKey = ${HOST_KEY}"
    out "Address = ${HOST_ADDR}/64"
    out "ListenPort = ${HOST_PORT}"
  } > 1-server.conf

  int=1
  for peer in "$@"; do
    int=$((int + 1))
    name="${int}-${peer}"

    PEER_ADDR=$(gen_ip "$int" "$peer")

    PSK=$(wg genpsk)

    PEER_KEY=$(wg genkey)
    PEER_PUB=$(printf %s "$PEER_KEY" | wg pubkey)

    {
      out

      out "[Peer]"
      out "PublicKey = ${PEER_PUB}"
      out "PresharedKey = ${PSK}"
      out "AllowedIPs = ${PEER_ADDR}/128"
    } >> 1-server.conf

    {
      out "[Interface]"
      out "PrivateKey = ${PEER_KEY}"
      out "Address = ${PEER_ADDR}/128"
      out "DNS = ${HOST_ADDR}"

      out

      out "[Peer]"
      out "PublicKey = ${HOST_PUB}"
      out "PresharedKey = ${PSK}"
      out "AllowedIPs = ${WG_PREFIX}::/64"
      out "Endpoint = ${WG_ENDPOINT}"
    } > "${name}.conf"

    qrencode -r "${name}.conf" -o "${name}.png"
  done
}

pkg() {
  cmd=$(command -v "$1")
  [ -x "$cmd" ]
}

out() {
  printf "%s\n" "$*"
}

die() {
  printf "%s: %s\n" "${0##*/}" "$*" >&2
  exit 1
}

while getopts o:e:p:P:g opt; do
  case $opt in
    o)
      OUTPUT="$OPTARG"
      ;;
    e)
      WG_ENDPOINT="$OPTARG"
      ;;
    p)
      HOST_PORT="$OPTARG"
      ;;
    P)
      WG_PREFIX="$OPTARG"
      ;;
    g)
      gen_pre
      exit
      ;;
    *)
      die "unknown option"
      ;;
  esac
done
shift $((OPTIND - 1))

if ! pkg wg; then
  die "wireguard-tools not installed"
fi

if ! pkg qrencode; then
  die "qrencode not installed"
fi

if [ $# -eq 0 ]; then
  die "peer name(s) required"
fi

if [ -z "$WG_ENDPOINT" ]; then
  die "endpoint required"
fi

if [ -z "$WG_PREFIX" ]; then
  WG_PREFIX=$(gen_pre)
fi

mkdir -m 700 "$OUTPUT"
cd -- "$OUTPUT"

gen_wg "$@"

column -t -o " " .unbound.conf > unbound.conf
rm .unbound.conf
