#!/bin/sh

ACT=/sys/class/leds/ACT/brightness
PWR=/sys/class/leds/PWR/brightness

on() {
  printf 1 > "$ACT"
  printf 1 > "$PWR"
}

off() {
  printf 0 > "$ACT"
  printf 0 > "$PWR"
}

toggle() {
  if [ "$(cat "$ACT")" != 0 ] || [ "$(cat "$PWR")" != 0 ]; then
    off
    printf "off\n"
  else
    on
    printf "on\n"
  fi
}

siren() {
  trap "off; exit 0" HUP INT TERM

  while true; do
    printf 1 > "$ACT"
    printf 0 > "$PWR"

    sleep 0.25

    printf 0 > "$ACT"
    printf 1 > "$PWR"

    sleep 0.25
  done
}

RST='\033[0;00m'
GRN='\033[0;32m'
YLW='\033[0;33m'

usage() {
  printf "%b\n" "${YLW}USAGE${RST}:"
  printf "%s\n" "    led [SUBCOMMAND]"
  printf "\n"
  printf "%b\n" "${YLW}SUBCOMMANDS${RST}:"
  printf "%b\n" "    ${GRN}1${RST}, ${GRN}on${RST}"
  printf "%b\n" "    ${GRN}0${RST}, ${GRN}off${RST}"
  printf "%b\n" "    ${GRN}t${RST}, ${GRN}toggle${RST}"
  printf "%b\n" "    ${GRN}!${RST}, ${GRN}siren${RST}"
}

case $1 in
  1 | on) on ;;
  0 | off) off ;;
  t | toggle) toggle ;;
  ! | siren) siren ;;
  *) usage ;;
esac
