#!/bin/sh

xbps-install -Syu
ret=$?

set -e

if [ $ret -ne 0 ]; then
  # error 16 means xbps needs to be updated
  if [ $ret -eq 16 ]; then
    xbps-install -yu xbps
    xbps-install -Syu
  else
    exit $ret
  fi
fi

xbps-remove -yo
xbps-remove -yO

curl -sS -o /etc/unbound/root.hints https://www.internic.net/domain/named.root
ln -f /etc/dns/root.key /etc/unbound/
