#!/bin/sh

set -e

PORT=51820

if [ $# -ne 3 ]; then
  printf "usage: wg-gen <peer_total> <address_block> <duckdns_subdomain>\n" >&2
  exit 1
fi

PEER_TOTAL="$1"
BLOCK="$2"
DUCK="$3"

ENDPOINT="${DUCK}.duckdns.org:${PORT}"

die() {
  printf "wg-gen: %s\n" "$*" >&2
  exit 1
}

# check

if ! command -v wg > /dev/null; then
  die "wireguard-tools not installed"
fi

if ! command -v qrencode > /dev/null; then
  die "qrencode not installed"
fi

if [ "$PEER_TOTAL" -gt 253 ]; then
  die "peer total cannot exceed 253"
fi

if [ -e wireguard ]; then
  die "directory 'wireguard': already exists"
fi

# server

install -d -m 700 wireguard

cd wireguard

SERVER_KEY=$(wg genkey)
SERVER_PUB=$(printf %s "$SERVER_KEY" | wg pubkey)

{
  printf "%s\n" "[Interface]"
  printf "%s\n" "Address = ${BLOCK}.1/24"
  printf "%s\n" "ListenPort = ${PORT}"
  printf "%s\n" "PrivateKey = ${SERVER_KEY}"
} > 1-server.conf

# peers

for peer in $(seq "$PEER_TOTAL"); do
  peer=$((peer + 1))

  PEER_KEY=$(wg genkey)
  PEER_PUB=$(printf %s "$PEER_KEY" | wg pubkey)

  PSK=$(wg genpsk)

  {
    printf "\n"
    printf "%s\n" "[Peer]"
    printf "%s\n" "PublicKey = ${PEER_PUB}"
    printf "%s\n" "PresharedKey = ${PSK}"
    printf "%s\n" "AllowedIPs = ${BLOCK}.${peer}/32"
  } >> 1-server.conf

  {
    printf "%s\n" "[Interface]"
    printf "%s\n" "Address = ${BLOCK}.${peer}/32"
    printf "%s\n" "PrivateKey = ${PEER_KEY}"
    printf "%s\n" "DNS = ${BLOCK}.1"

    printf "\n"

    printf "%s\n" "[Peer]"
    printf "%s\n" "PublicKey = ${SERVER_PUB}"
    printf "%s\n" "PresharedKey = ${PSK}"
    printf "%s\n" "Endpoint = ${ENDPOINT}"
    printf "%s\n" "AllowedIPs = ${BLOCK}.0/24"
  } > "$peer".conf

  qrencode -r "$peer".conf -o "$peer".png
done
